# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58870ab0ffbc8b47f417ab397cc91c6a53a62c44465adceb297bbede1dab31aa5789e1ca2e556f31d0089fb38fd5bc69e291fa23cb91c963ba8814dea4688eaf

test:
  secret_key_base: fa4aadaddbad32fc0ab0bd419d483647205d9d98f06c6e81c8a903f6a51003c2b2fdd0f8a5732a6fb4fd6558342b9a0501b78850c10f1603b4ec2248c6071b32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
